name: google-drive-prototype
runtime: python

command:
  - streamlit
  - run
  - google_drive_prototype.py

env:
  DATABRICKS_HOST:
    secret:
      scope: app-secrets
      key: DATABRICKS_HOST
  DATABRICKS_TOKEN:
    secret:
      scope: app-secrets
      key: DATABRICKS_TOKEN
  STREAMLIT_SERVER_HEADLESS: "true"
  STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"

